[master]
k8s-master ansible_host=98.92.62.34 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/k8s.pem

[workers]
k8s-worker-1 ansible_host=34.201.5.33 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/k8s.pem
k8s-worker-2 ansible_host=100.24.107.227 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/k8s.pem

[all:children]
master
workers
